branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: active_elastic_job
  default_ec2_keyname: null
  default_platform: Ruby 2.6 (Passenger Standalone)
  default_region: us-east-1
  sc: null
