source 'https://rubygems.org'

gem 'rails', '~> 4.2'
gem 'sqlite3'
gemspec :path => '../'
gem 'bundler'
gem 'rspec', '~> 3.4'
gem 'dotenv'
gem 'fuubar'
gem 'rdoc'
gem 'benchmark-ips'
gem 'climate_control'
